### ISSUE TITLE
[Question] What is olympusnews/index.txt used for?

### ISSUE THREAD

**Issue by tristan-f-r** [EverestAPI/EverestAPI.github.io#13]
I was looking at the workflows for this website and was curious about why the news is indexed when the actual website itself doesn't use the articles at all - is this being used in another repository?

**Comment by maddie480** [comment]
Olympus news aren't used on the website itself, yeah 😅 they are used in Olympus, though: https://github.com/EverestAPI/Olympus/blob/main/src/scenes/mainmenu.lua#L586

**Comment by tristan-f-r** [comment]
Thanks for the response! It would be quite cool if the news articles were displayed on the website as well then :+1: (this was _not_ the original goal of this issue, more as a genuine question, but I would be happy to implement this!)
